/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zavrsnirad.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import zavrsnirad.utility.Utils;

/**
 *
 * @author mirza
 */
public class ViewGlavni extends javax.swing.JFrame {

    /**
     * Creates new form Glavni
     */
    public ViewGlavni() {
        initComponents();
        new Vrijeme().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKlijentiKupci = new javax.swing.JButton();
        btnProizvodiUsluge = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        lblTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnIspis = new javax.swing.JButton();
        btnUredi = new javax.swing.JButton();
        btnObriši = new javax.swing.JButton();
        btnNoviRačun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        btnKalkulator = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPostavke = new javax.swing.JMenu();
        jMenuItemDBserver = new javax.swing.JMenuItem();
        jMenuObrt = new javax.swing.JMenuItem();
        jMenuPomoc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PO Glavni prozor");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Uređivanje ..."));

        btnKlijentiKupci.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKlijentiKupci.setText("Klijenti/Kupci");
        btnKlijentiKupci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentiKupciActionPerformed(evt);
            }
        });

        btnProizvodiUsluge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProizvodiUsluge.setText("Proizvodi / Usluge");
        btnProizvodiUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProizvodiUslugeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKlijentiKupci, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnProizvodiUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKlijentiKupci, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProizvodiUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        lblTime.setText("Time");
        jToolBar1.add(lblTime);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RAČUN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnIspis.setText("Ispis");

        btnUredi.setText("Uredi");

        btnObriši.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnObriši.setForeground(new java.awt.Color(204, 0, 0));
        btnObriši.setText("Obriši");
        btnObriši.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrišiActionPerformed(evt);
            }
        });

        btnNoviRačun.setText("NOVI račun");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 276, Short.MAX_VALUE)
                        .addComponent(btnNoviRačun, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIspis, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUredi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObriši, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIspis)
                    .addComponent(btnUredi)
                    .addComponent(btnObriši)
                    .addComponent(btnNoviRačun))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alati ..."));

        btnKalkulator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKalkulator.setText("Kalkulator");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuPostavke.setText("Postavke");

        jMenuItemDBserver.setText("DB server");
        jMenuItemDBserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDBserverActionPerformed(evt);
            }
        });
        jMenuPostavke.add(jMenuItemDBserver);

        jMenuObrt.setText("Podaci o obrtu");
        jMenuObrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuObrtActionPerformed(evt);
            }
        });
        jMenuPostavke.add(jMenuObrt);

        jMenuBar1.add(jMenuPostavke);

        jMenuPomoc.setText("Pomoč");
        jMenuBar1.add(jMenuPomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrišiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrišiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrišiActionPerformed

    private void jMenuObrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuObrtActionPerformed
        new ViewPodaciOObrtu().setVisible(true);
    }//GEN-LAST:event_jMenuObrtActionPerformed

    private void btnKlijentiKupciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentiKupciActionPerformed
        new ViewKlijentKupac().setVisible(true);
    }//GEN-LAST:event_btnKlijentiKupciActionPerformed

    private void btnProizvodiUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProizvodiUslugeActionPerformed
        new ViewProizvodUsluga().setVisible(true);
    }//GEN-LAST:event_btnProizvodiUslugeActionPerformed

    private void jMenuItemDBserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDBserverActionPerformed
        new ViewDBserverPodaci().setVisible(true);
    }//GEN-LAST:event_jMenuItemDBserverActionPerformed
    private class Vrijeme extends Thread{
        SimpleDateFormat vrijemeFormat =new SimpleDateFormat(Utils.getFormatDatumaIVremena());
    @Override
    public void run(){
        lblTime.setText(vrijemeFormat.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
               
            }
            run();
    }       
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIspis;
    private javax.swing.JButton btnKalkulator;
    private javax.swing.JButton btnKlijentiKupci;
    private javax.swing.JButton btnNoviRačun;
    private javax.swing.JButton btnObriši;
    private javax.swing.JButton btnProizvodiUsluge;
    private javax.swing.JButton btnUredi;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDBserver;
    private javax.swing.JMenuItem jMenuObrt;
    private javax.swing.JMenu jMenuPomoc;
    private javax.swing.JMenu jMenuPostavke;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
