/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zavrsnirad.view;

import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import zavrsnirad.controller.ObradaStavka;
import zavrsnirad.controller.ObradaUsluga_proizvod;
import zavrsnirad.model.Racun;
import zavrsnirad.model.Stavka;
import zavrsnirad.model.Usluga_proizvod;

/**
 *
 * @author mirza
 */
public class ViewRacun extends javax.swing.JFrame {
    private ViewGlavni glavni;
    private Racun r;
    private ObradaStavka obrada;
    /**
     * Creates new form ViewRacun
     */
    public ViewRacun(ViewGlavni r) {
        initComponents();
        this.glavni=r;
        this.r=glavni.getOdabraniRacun();
        ButtonGroup group=new ButtonGroup();
        group.add(rbtRobaDomaci);
        group.add(rbtRobaInozemni);
        group.add(rbtUslugeDomaci);
        group.add(rbtUslugeInozemni);
        if(this.r.getId()==null){
            
        }else{
            ucitajRacun();
        }
        
        ucitajUsluge();
        
    }
    private void ucitajRacun(){
        txtBrojRacuna.setText(r.getBroj_racuna());
        dtcVrijemeIzdavanja.setDate(r.getDatum_izdavanja());
        dtcDatumIsporuke.setDate(r.getDatum_isporuke());
        txtIzdaoKorisnik.setText(r.getKorisnik().getPrezime());
        txtKupac.setText(r.getKlijent_kupac().getNaziv());
        txtNacinPlacanja.setText(r.getNacin_placanja());
        dtcDatumDospijeca.setDate(r.getDatum_dospijeca());
        txtfNapomena.setText(r.getNapomena());
        
        DefaultTableModel dtm=(DefaultTableModel)tblStavke.getModel();
        List<Stavka> stavke=r.getStavke();
        String[] colNames = {"objekt", "Naziv", "Jed. mj.", "Cijena", "Kolićina", "Rabat", "Iznos"};
         for (int i = 0; i < colNames.length; i++) {
            
            TableColumn tc = tblStavke.getColumnModel().getColumn(i);
            tc.setHeaderValue(colNames[i]);
            if (i == 0) {
                tc.setWidth(0);
                tc.setMinWidth(0);
                tc.setMaxWidth(0);
            }
        }
        for(Stavka s:stavke){
            
            Object []red={
                s,
                s.getProizvod().getNaziv(),
                s.getProizvod().getJedinica_mjere(),
                s.getProizvod().getCijena().toString(),
                s.getKolicina(),
                s.getRabat(),
                s.getIznosStavke()
               
                
            };
            dtm.addRow(red);
        }
        
        txtUkupno.setText(r.getIznos_racuna().toString()+" HRK");
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGroup = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfNapomena = new javax.swing.JTextArea();
        txtBrojRacuna = new javax.swing.JTextField();
        txtKupac = new javax.swing.JTextField();
        txtIzdaoKorisnik = new javax.swing.JTextField();
        txtNacinPlacanja = new javax.swing.JTextField();
        rbtUslugeDomaci = new javax.swing.JRadioButton();
        rbtUslugeInozemni = new javax.swing.JRadioButton();
        rbtRobaDomaci = new javax.swing.JRadioButton();
        rbtRobaInozemni = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnSpremi = new javax.swing.JButton();
        btnSpremiIIspisi = new javax.swing.JButton();
        btnIIspisi = new javax.swing.JButton();
        btnObrisi1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dtcVrijemeIzdavanja = new com.toedter.calendar.JDateChooser();
        dtcDatumDospijeca = new com.toedter.calendar.JDateChooser();
        dtcDatumIsporuke = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        comStavkaNaziv = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStavkaJedinicaMjere = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStavkaCijena = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        spnStavkaKolicina = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        txtStavkaRabat = new javax.swing.JTextField();
        txtStavkaIznos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStavkaOpis = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnStavkaDodaj = new javax.swing.JButton();
        btnStavkaSpremi = new javax.swing.JButton();
        btnStavkaObrisi = new javax.swing.JButton();
        txtUkupno = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 539));
        setSize(new java.awt.Dimension(1300, 539));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Račun ..."));

        jLabel1.setText("Broj računa:");

        jLabel2.setText("Klijent / Kupac:");

        jLabel3.setText("Vrijeme izdavanja:");

        jLabel4.setText("Datum dospijeća:");

        jLabel5.setText("Datum isporuke:");

        jLabel6.setText("Izdao korisnik:");

        jLabel7.setText("Napomena:");

        jLabel8.setText("Način plačanja:");

        txtfNapomena.setColumns(20);
        txtfNapomena.setRows(5);
        jScrollPane1.setViewportView(txtfNapomena);

        rbtUslugeDomaci.setSelected(true);
        rbtUslugeDomaci.setText("Usluge:Domaći");
        rbtUslugeDomaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtUslugeDomaciActionPerformed(evt);
            }
        });

        rbtUslugeInozemni.setText("Usluge:Inozemni");
        rbtUslugeInozemni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtUslugeInozemniActionPerformed(evt);
            }
        });

        rbtRobaDomaci.setText("Roba:Domaći");
        rbtRobaDomaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRobaDomaciActionPerformed(evt);
            }
        });

        rbtRobaInozemni.setText("Roba:Inozemni");
        rbtRobaInozemni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRobaInozemniActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke ..."));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stavka", "Naziv", "jed.mj.", "Cijena", "Količina", "Rabat", "Iznos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStavke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStavkeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblStavke);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        btnSpremiIIspisi.setText("Spremi i ispiši");
        btnSpremiIIspisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiIIspisiActionPerformed(evt);
            }
        });

        btnIIspisi.setText("Ispiši");
        btnIIspisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIIspisiActionPerformed(evt);
            }
        });

        btnObrisi1.setText("Obriši");
        btnObrisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisi1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("UKUPNO:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Odabrana stavka ..."));

        comStavkaNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comStavkaNazivActionPerformed(evt);
            }
        });

        jLabel10.setText("Naziv stavke");

        jLabel11.setText("Jedinica mjere:");

        jLabel12.setText("Cijena");

        jLabel14.setText("Količina");

        jLabel15.setText("Rabat (%)");

        txtStavkaIznos.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("IZNOS");

        txtStavkaOpis.setColumns(20);
        txtStavkaOpis.setRows(5);
        jScrollPane2.setViewportView(txtStavkaOpis);

        jLabel16.setText("Opis:");

        btnStavkaDodaj.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStavkaDodaj.setText("Dodaj stavku");
        btnStavkaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStavkaDodajActionPerformed(evt);
            }
        });

        btnStavkaSpremi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStavkaSpremi.setText("Spremi promjenu");
        btnStavkaSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStavkaSpremiActionPerformed(evt);
            }
        });

        btnStavkaObrisi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStavkaObrisi.setText("Obriši stavku");
        btnStavkaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStavkaObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comStavkaNaziv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStavkaRabat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtStavkaIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStavkaCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStavkaJedinicaMjere, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnStavkaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStavkaSpremi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStavkaDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnStavkaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comStavkaNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtStavkaJedinicaMjere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtStavkaCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(spnStavkaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtStavkaRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtStavkaIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStavkaDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStavkaSpremi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnStavkaObrisi))
        );

        txtUkupno.setEditable(false);
        txtUkupno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtUkupno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUkupno.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        txtUkupno.setEnabled(false);
        txtUkupno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUkupnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnIIspisi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSpremi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSpremiIIspisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtUslugeInozemni)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtUslugeDomaci)
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtRobaInozemni)
                                            .addComponent(rbtRobaDomaci)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtKupac)
                                        .addComponent(txtBrojRacuna)
                                        .addComponent(dtcVrijemeIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtIzdaoKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dtcDatumIsporuke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(dtcDatumDospijeca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(25, 25, 25))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(dtcVrijemeIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dtcDatumDospijeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(dtcDatumIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtIzdaoKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtUslugeDomaci)
                                    .addComponent(rbtRobaDomaci))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtUslugeInozemni)
                                    .addComponent(rbtRobaInozemni)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(btnSpremi)
                                .addGap(18, 18, 18)
                                .addComponent(btnSpremiIIspisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIIspisi)
                                    .addComponent(btnObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStavkaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStavkaObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStavkaObrisiActionPerformed

    private void btnStavkaSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStavkaSpremiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStavkaSpremiActionPerformed

    private void btnStavkaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStavkaDodajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStavkaDodajActionPerformed

    private void comStavkaNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comStavkaNazivActionPerformed
        Usluga_proizvod p=(Usluga_proizvod) comStavkaNaziv.getSelectedItem();
        txtStavkaCijena.setText(p.getCijena().toString());
        txtStavkaJedinicaMjere.setText(p.getJedinica_mjere());
        txtStavkaOpis.setText(p.getOpis());
    }//GEN-LAST:event_comStavkaNazivActionPerformed

    private void btnObrisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisi1ActionPerformed

    private void btnIIspisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIIspisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIIspisiActionPerformed

    private void btnSpremiIIspisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiIIspisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpremiIIspisiActionPerformed

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        //provjera da li racun postoji
        //upozori ako je isti broj
        //ako nije spremi ga sa novim brojem
        
        
        //na kraju
        glavni.ucitaj();
        dispose();
    }//GEN-LAST:event_btnSpremiActionPerformed

    private void tblStavkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStavkeMouseClicked
        
         
        Stavka s = (Stavka) tblStavke.getValueAt(tblStavke.getSelectedRow(), 0);
        //System.out.println(tblStavke.getValueAt(tblStavke.getSelectedRow(), 0));
        //comStavkaNaziv.setSelectedItem(s.getProizvod().getNaziv());
        comStavkaNaziv.setSelectedIndex(s.getId());
        txtStavkaCijena.setText(s.getProizvod().getCijena().toString());
        txtStavkaJedinicaMjere.setText(s.getProizvod().getJedinica_mjere());
        spnStavkaKolicina.setValue(s.getKolicina());
        txtStavkaOpis.setText(s.getProizvod().getOpis());
        txtStavkaIznos.setText(""+s.getIznosStavke());
    }//GEN-LAST:event_tblStavkeMouseClicked

    private void rbtRobaInozemniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRobaInozemniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtRobaInozemniActionPerformed

    private void rbtRobaDomaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRobaDomaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtRobaDomaciActionPerformed

    private void rbtUslugeInozemniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtUslugeInozemniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtUslugeInozemniActionPerformed

    private void rbtUslugeDomaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtUslugeDomaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtUslugeDomaciActionPerformed

    private void txtUkupnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUkupnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUkupnoActionPerformed

    private void ucitajProizvodeUsluge() {

        DefaultComboBoxModel<Usluga_proizvod> m = new DefaultComboBoxModel<>();
        Usluga_proizvod up = new Usluga_proizvod();
        up.setId(0);
        up.setNaziv("Odaberite proizvod");
        m.addElement(up);
        
        new ObradaUsluga_proizvod().getEntiteti().forEach((uslugaProizvod) -> {
            m.addElement(uslugaProizvod);
        });
        comStavkaNaziv.setModel(m);
        
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIIspisi;
    private javax.swing.JButton btnObrisi1;
    private javax.swing.JButton btnSpremi;
    private javax.swing.JButton btnSpremiIIspisi;
    private javax.swing.JButton btnStavkaDodaj;
    private javax.swing.JButton btnStavkaObrisi;
    private javax.swing.JButton btnStavkaSpremi;
    private javax.swing.ButtonGroup btngGroup;
    private javax.swing.JComboBox<Usluga_proizvod> comStavkaNaziv;
    private com.toedter.calendar.JDateChooser dtcDatumDospijeca;
    private com.toedter.calendar.JDateChooser dtcDatumIsporuke;
    private com.toedter.calendar.JDateChooser dtcVrijemeIzdavanja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rbtRobaDomaci;
    private javax.swing.JRadioButton rbtRobaInozemni;
    private javax.swing.JRadioButton rbtUslugeDomaci;
    private javax.swing.JRadioButton rbtUslugeInozemni;
    private javax.swing.JSpinner spnStavkaKolicina;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojRacuna;
    private javax.swing.JTextField txtIzdaoKorisnik;
    private javax.swing.JTextField txtKupac;
    private javax.swing.JTextField txtNacinPlacanja;
    private javax.swing.JTextField txtStavkaCijena;
    private javax.swing.JTextField txtStavkaIznos;
    private javax.swing.JTextField txtStavkaJedinicaMjere;
    private javax.swing.JTextArea txtStavkaOpis;
    private javax.swing.JTextField txtStavkaRabat;
    private javax.swing.JTextField txtUkupno;
    private javax.swing.JTextArea txtfNapomena;
    // End of variables declaration//GEN-END:variables

    private void ucitajUsluge() {
        DefaultComboBoxModel<Usluga_proizvod> m = new DefaultComboBoxModel<>();
        Usluga_proizvod pr = new Usluga_proizvod();
        pr.setId(0);
        pr.setNaziv("Odaberite");
        m.addElement(pr);

        new ObradaUsluga_proizvod().getEntiteti().forEach((p) -> {
            m.addElement(p);
        });
        comStavkaNaziv.setModel(m);
        
        
    }
}
